### ISSUE TITLE
Default value for 'token_user' is being set to string containing 'None'

### ISSUE THREAD

**Issue by dalarsen** [StackStorm-Exchange/github#54]
https://github.com/StackStorm-Exchange/stackstorm-github/blob/7a6e159b9313e8e5df484e06829b5fea646211da/actions/get_user.yaml#L15

When calling this action without a token_user and without an action_context.api_user, the default parameter specified is for some reason being evaluated into a string "None" instead of the None object.  This causes the code block for "if token_user:" to be evaluated as True and causes it to run the _change_to_user_token method to be run when it aught not be (in my organization, it leads to an unauthenticated request and causes it to crash, though I imagine this wouldn't universally be the consequence of this).

Raising as an issue here, please let me know if you'd like me to raise a PR with the fix.  I corrected the issue for the code that I'm using by changing the line to this - i'm sure there could be other fixes as well:

default: "{{action_context.api_user|default()}}"

**Comment by dalarsen** [comment]
Here's the output of the action showing what happens when attempting to use the action:

{
  "stdout": "",
  "stderr": "st2.actions.python.GetUserAction: DEBUG    Creating new Client object.
st2.actions.python.GetUserAction: DEBUG    Retrieving value from the datastore (name=github.GetUserAction:token_enterprise_None)
st2.actions.python.GetUserAction: DEBUG    Retrieving value from the datastore (name=github.GetUserAction:token_enterprise_None)
Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py\", line 395, in <module>
    obj.run()
  File \"/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py\", line 214, in run
    output = action.run(**self._parameters)
  File \"/opt/stackstorm/packs.dev/github/actions/get_user.py\", line 16, in run
    return self.token + \" \" + str(self._client.__dict__) + str(self._client.get_user(\"dalarsen\")) + str(
  File \"/opt/stackstorm/virtualenvs/github/lib/python3.8/site-packages/github/MainClass.py\", line 263, in get_user
    headers, data = self.__requester.requestJsonAndCheck(
  File \"/opt/stackstorm/virtualenvs/github/lib/python3.8/site-packages/github/Requester.py\", line 320, in requestJsonAndCheck
    return self.__check(
  File \"/opt/stackstorm/virtualenvs/github/lib/python3.8/site-packages/github/Requester.py\", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {\"message\": \"API rate limit exceeded for 17x.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\", \"documentation_url\": \"https://docs.github.com/enterprise-server@3.8/rest/overview/resources-in-the-rest-api#rate-limiting\"}
",
  "exit_code": 1,
  "result": "None"
}

**Comment by arm4b** [comment]
Yeah, that sounds like a bug. Definitely submit a PR to fix it!
